spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:55008/accounts
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false